// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { meta, metaRequest, metaResponse } from './meta';
import { article, articleRequest, articleResponse } from './article';

/**
 * The shape of the model inside the application code - what the users use
 */
export const response = z.object({
  meta: meta.optional(),
  docs: z.array(article).optional(),
});

/**
 *
 * @typedef  {Response} response
 * @property {Meta}
 * @property {Article[]}
 */
export type Response = z.infer<typeof response>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const responseResponse = z
  .object({
    meta: metaResponse.optional(),
    docs: z.array(articleResponse).optional(),
  })
  .transform((data) => ({
    meta: data['meta'],
    docs: data['docs'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const responseRequest = z
  .object({ meta: metaRequest.nullish(), docs: z.array(articleRequest).nullish() })
  .transform((data) => ({
    meta: data['meta'],
    docs: data['docs'],
  }));
